stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: alpine:latest
  before_script:
    - apk add npm git tar
    - npm ci
  script:
    - echo $CI_COMMIT_SHA > version
    - tar -cf app.tar --exclude-vcs --exclude=app.tar .
  artifacts:
    paths:
      - app.tar

include:
  - project: ci-modulize/kubernetes
    file:
      - package.yml
      - deploy.yml
