stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: alpine:edge
  before_script:
    - apk add npm git tar
    - npm ci
  script:
    - echo $CI_COMMIT_SHA > version
    - tar -cf app.tar --exclude-vcs --exclude=app.tar .
  artifacts:
    paths:
      - app.tar

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:production
  only:
    - master

deploy:
  stage: deploy
  image:
    name: alpine:latest
  environment:
    name: production
  before_script:
    - apk add gettext
    - wget https://storage.googleapis.com/kubernetes-release/release/v1.17.9/bin/linux/amd64/kubectl
    - chmod +x kubectl
  script:
    - ./kubectl -n $KUBE_NAMESPACE create secret generic ${CI_PROJECT_PATH_SLUG}-secrets --from-file=token=$TOKEN --dry-run -o yaml | ./kubectl -n $KUBE_NAMESPACE apply -f -
    - envsubst < deployment.yml > out.yml
    - ./kubectl -n $KUBE_NAMESPACE apply -f out.yml
