apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-voice-channel-bot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: discord-voice-channel-bot
          image: registry.eglo.ga/none
          volumeMounts:
            - name: secrets
              mountPath: /srv/token
              subPath: token
      volumes:
        - name: secrets
          secret:
            secretName: secrets
